### PR TITLE
Auto clean directory

### PR DESCRIPTION
**Pull request by cedvan**
Auto clean directory path
Remove tracks missing in playlists
Remove empty directories

### CODE REVIEW

**Comment by anatosun** [comment]
I am not so sure removing tracks no longer in any playlist is something that every user would like.  I think this functionality should rather be implemented as part of a new command, e.g., `clean`.

**Comment by cedvan** [comment]
Hmm, maybe a new config setting then `autoClean: true/false`

**Comment by anatosun** [comment]
I will think about it this afternoon. I understand the practical aspect of having one command to download and clean. However, in my opinion, commands should define and separate the logic of the program.

**Comment by cedvan** [comment]
Separating the commands risks complicating the code, in fact, currently I use loops during downloading to tag the retrieved files. 

However it doesn't make sense to update playlist files and remove references to tracks, and not remove those tracks. But that's just my opinion

If you want to separate it. It will be necessary to redevelop a complete section of get plex information and loops to identify the pieces still present in the playlists and those to be cleaned.

Personaly I use batch file to automate my system. So, add a second command "clean" after the "refresh" command is not a problem for me.

But keeping the name "refresh" for the command seems illogical to me. Indeed "refresh" supposes updating the local folders, so that an auto clean comes with it is logical. If there is no autoclean, then the "refresh" command should be "download" to keep the logic correct

I can suggest otherwise:

- "download" command: only download missing tracks and update playlists
- "clean" command: clean missing files in playlists
- "refresh" command: download + clean

**Comment by anatosun** [comment]
I think you're right about this possible redundancy of getting the information from Plex. I suggest using a flag like `--clear` to clean up non-referenced files then.

**Comment by cedvan** [comment]
Ok, I added the "--clear" flag and rebased the commits to respect Conventional Commits

**Comment by cedvan** [comment]
Oh sorry, miss documentation, I will add ;)

**Comment by cedvan** [comment]
Ok, work is done

**Comment by cedvan** [comment]
I wonder if we shouldn't have a --no-clear flag instead. The case of clear automatic is still used more I think.

**Pull request merged**
