### PR TITLE
Optimize command options

### PR DESCRIPTION
**Pull request by cedvan**
Optimize command logic :

- `plex2mix enable X` : enable playlist X
- `plex2mix ignore X` : ignore (disable) playlist X
- `plex2mix download` : download enabled playlists and related tracks
- `plex2mix refresh` : is alias to download to keep retro compatibility

Merge PR before : https://github.com/anatosun/plex2mix/pull/5

### CODE REVIEW

**Comment by cedvan** [comment]
Rebased from main, ready to review and merge

**Comment by cedvan** [comment]
`I like the idea of having a command that only saves the playlist., but I like that it echoes the save key of the config. Also, I think we don't need to maintain retrocompatibility at this stage of the project. My commit addresses that.`

I'm not sure I understood. Should I correct something?

**Comment by anatosun** [comment]
No no I just did the adjustments

**Comment by cedvan** [comment]
Oh sorry, I pushed force to rebase.
I had to overwrite your changes? can you repush please?

**Pull request closed without merging**
