### PR TITLE
Generate itunes xml

### PR DESCRIPTION
**Pull request by cedvan**
- Tracks done
  - Rating OK
  - Year OK (from album)
  - Genres OK (from album) 
- Playlists done

*Optimize clear and add clear playlists ignored*

### CODE REVIEW

**Comment by cedvan** [comment]
Before merge, need merge other PRs : 
- https://github.com/anatosun/plex2mix/pull/5
- https://github.com/anatosun/plex2mix/pull/6
- https://github.com/anatosun/plex2mix/pull/7

**Comment by cedvan** [comment]
Tested with rekordbox, work like a charm 😄  !!

**Comment by cedvan** [comment]
Now, just create a `.bat` file to launch `plex2mix download`. Execute this .bat and just reload itunes in rekordbox (traktor, virtualDJ, Serato, etc...) to update DJ sets :)

**Comment by anatosun** [comment]
Nice work! Will have a look over the weekend. Looks exciting :)

It'd be great if you could also use conventional commits nomenclature: https://www.conventionalcommits.org/en/v1.0.0/

**Comment by cedvan** [comment]
this is my first lines of code in python, don't hesitate to tell me if it's not correct

**Comment by anatosun** [comment]
Yes, but wait until I review your code to change it. Great to see people getting into programming with this projection!

**Comment by cedvan** [comment]
I am not an apprentice developer, I am an architect and professional CTO in the world of PHP/Javascript. But I had never done python yet :)

**Comment by anatosun** [comment]
Yes, I meant more programming in Python! :)

**Comment by anatosun** [comment]
It would be great to streamline both the m3u8 and the xml export. I'm thinking of maybe providing an interface that could  be implemented by both the m3u8 and the xml exporter?

I can work on that directly on your PR if you want.

**Comment by cedvan** [comment]
I get the idea, but I'm not sure it makes sense. iTunes XML is very particular, it has its own approach, which in my opinion is even bad sometimes.

**Comment by cedvan** [comment]
But you can try on this PR. It is up to date and rebased on the modifications made to the other PRs.

**Comment by cedvan** [comment]
I can suggest, maybe resolve and merge other PR before ?

**Comment by cedvan** [comment]
Why merge ? THis PR was based from https://github.com/anatosun/plex2mix/pull/7, itself based on https://github.com/anatosun/plex2mix/pull/5

**Comment by cedvan** [comment]
juste approve and merge https://github.com/anatosun/plex2mix/pull/7 and next rebase from main

**Comment by anatosun** [comment]
I felt fixing the bad char problem was sufficiently urgent for me to merge directly. I'm not sure to be able to review the other PRs today, that's also why.

**Comment by cedvan** [comment]
I understand, the https://github.com/anatosun/plex2mix/pull/7 is very simple. Just update command options to keep your vision : 1 option to 1 feature.

**Comment by anatosun** [comment]
Would you have a mockup iTunes XML for me to check the format?

**Comment by cedvan** [comment]
https://gist.github.com/cedvan/526e56f122f7f0d37f565979ff5a2db2

**Comment by cedvan** [comment]
Hello,

Good work, use ratingKey is a good idea to itunes ID :)

Tested on main with other fix commits.

4 Problems :
- Playlists itunes array is malformed, miss `dict` session for each playlist
- array `Playlist Items` is not provided in itunes playlists, it stay empty. So all playlists stay empty
- Normalization don't work correctly to the tracks with `/` in title like `AC/DC`
- To support multiple plex servers with plex2mix,  itunes `Library Persistent ID` must be unique between plex servers. So use `plex2mix` is not a good idea. Use plex server URL or plex server name will be better

2 questions : 

- Why did you remove clean system to the playlists ignored? (If I ignore a playlist after saving it, it will not be deleted)
- Why did you keep the click alias library when it is not used?

**Pull request merged**
